services:
  webserver:
    container_name: webserver
    image: nginx:latest
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./workspace:/var/www/html/workspace
    depends_on:
      - php-xdebug

  php-xdebug:
    container_name: php-xdebug
    build: ./php/
    volumes:
      - ./workspace:/var/www/html/workspace